apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles
  labels:
    app: candles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles
  template:
    metadata:
      labels:
        app: candles
    spec:
      containers:
        - name: candles
          image: candles:dev
          imagePullPolicy: Never # Use the local image
          env:
            - name: KAFKA_BROKER_ADDRESS
              value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: KAFKA_TOPIC
              value: "candles"
