apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-historical
  namespace: hist-svcs
  labels:
    app: trades-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades-historical
  template:
    metadata:
      labels:
        app: trades-historical
    spec:
      containers:
        - name: trades-historical
          image: trades:dev
          imagePullPolicy: Never # Use the local image
          env:
            - name: KAFKA_BROKER_ADDRESS
              value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: KAFKA_TOPIC
              value: "trades_historical"
            - name: HISTORICAL_DATA
              value: "True"
            - name: SINCE_DAYS
              value: "30"
