apiVersion: v1
kind: ConfigMap
metadata:
  name: hist-svcs-config
  namespace: hist-svcs
data:
  KAFKA_BROKER_ADDRESS: "kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092"
  TRADES_TOPIC: "trades_historical"
  CANDLES_TOPIC: "candles_historical"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: trades-historical
  namespace: hist-svcs
  labels:
    app: trades-historical
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: trades-historical
    spec:
      restartPolicy: OnFailure
      containers:
        - name: trades-historical
          image: trades:dev
          imagePullPolicy: Never # Use the local image
          env:
            - name: KAFKA_BROKER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: hist-svcs-config
                  key: KAFKA_BROKER_ADDRESS
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: hist-svcs-config
                  key: TRADES_TOPIC
            - name: HISTORICAL_DATA
              value: "True"
            - name: SINCE_DAYS
              value: "90"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: candles-historical
  namespace: hist-svcs
  labels:
    app: candles-historical
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: candles-historical
    spec:
      restartPolicy: OnFailure
      containers:
        - name: candles-historical
          image: candles:dev
          imagePullPolicy: Never # Use the local image
          env:
            - name: KAFKA_BROKER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: hist-svcs-config
                  key: KAFKA_BROKER_ADDRESS
            - name: KAFKA_INPUT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: hist-svcs-config
                  key: TRADES_TOPIC
            - name: KAFKA_OUTPUT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: hist-svcs-config
                  key: CANDLES_TOPIC
            - name: KAFKA_CONSUMER_GROUP
              value: "candles_consumer_group"
            - name: CANDLE_DURATION
              value: "60"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: technical-indicators-historical
  namespace: hist-svcs
  labels:
    app: technical-indicators-historical
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: technical-indicators-historical
    spec:
      restartPolicy: OnFailure
      containers:
        - name: technical-indicators-historical
          image: technical_indicators:dev
          imagePullPolicy: Never # Use the local image
          env:
            - name: KAFKA_BROKER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: hist-svcs-config
                  key: KAFKA_BROKER_ADDRESS
            - name: KAFKA_INPUT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: hist-svcs-config
                  key: CANDLES_TOPIC
            - name: KAFKA_OUTPUT_TOPIC
              value: "technical-indicators"
            - name: KAFKA_CONSUMER_GROUP
              value: "technical-indicators-consumer-group"
            - name: CANDLE_DURATION
              value: "60"
            - name: MAX_CANDLES
              value: "70"
