apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical_indicators
  labels:
    app: technical_indicators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technical_indicators
  template:
    metadata:
      labels:
        app: technical_indicators
    spec:
      containers:
        - name: technical_indicators
          image: technical_indicators:dev
          imagePullPolicy: Never # Use the local image
          env:
            - name: KAFKA_BROKER_ADDRESS
              value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: KAFKA_INPUT_TOPIC
              value: "candles"
            - name: KAFKA_OUTPUT_TOPIC
              value: "technical_indicators"
            - name: KAFKA_CONSUMER_GROUP
              value: "technical_indicators_consumer_group"
            - name: CANDLE_DURATION
              value: "60"
            - name: MAX_CANDLES
              value: "10"
